import {
  Wifi,
  BedSingle,
  Utensils,
  ParkingCircle,
  ParkingSquare,
  Bath,
  ShowerHead,
  Tv,
  ShieldCheck,
  UserCheck,
  Leaf,
  Sun,
  Sofa,
  Smile,
  CookingPot,
  Fan,
  Droplets,
  Eye,
  SquareGanttChart,
  CircleDashed,
  WandSparkles,
  Ruler,
  DoorOpen,
  DoorClosed,
  Thermometer,
  Soup,
  Building2,
  Flame,
  Toilet,
  Users2,
  CheckCircle,
  LucideIcon,
} from "lucide-react";

export const RULE_ICONS: Record<string, { label: string; icon: LucideIcon }> = {
  // Kategori Kost
  WiFi: { label: "WiFi", icon: Wifi },
  Balcon: { label: "Balkon", icon: DoorOpen },
  "Parkir Motor": { label: "Parkir Motor", icon: ParkingCircle },
  "Parkir Mobil": { label: "Parkir Mobil", icon: ParkingSquare },
  "Dapur Bersama": { label: "Dapur Bersama", icon: Utensils },
  Dispenser: { label: "Dispenser", icon: Soup },
  Jemuran: { label: "Jemuran", icon: Sun },
  "K. Mandi Luar": { label: "Kamar Mandi Luar", icon: DoorClosed },
  Kompor: { label: "Kompor", icon: CookingPot },
  // "Mesin Cuci": { label: "Mesin Cuci", icon: Washer },
  // Kulkas: { label: "Kulkas", icon: Fridge },
  TV: { label: "TV", icon: Tv },
  CCTV: { label: "CCTV", icon: ShieldCheck },
  "Penjaga Kos": { label: "Penjaga Kos", icon: UserCheck },
  "Pengurus Kos": { label: "Pengurus Kos", icon: Users2 },
  // Laundry: { label: "Laundry", icon: Washer },
  "R. Keluarga": { label: "Ruang Keluarga", icon: Sofa },
  "R. Jemur": { label: "Ruang Jemur", icon: Sun },
  "R. Santai": { label: "Ruang Santai", icon: Smile },
  Taman: { label: "Taman", icon: Leaf },
  Rooftop: { label: "Rooftop", icon: Building2 },

  // Kategori Kamar
  // Cermin: { label: "Cermin", icon: Mirror },
  "Cleaning service": { label: "Cleaning Service", icon: WandSparkles },
  "Dapur Pribadi": { label: "Dapur Pribadi", icon: Utensils },
  Jendela: { label: "Jendela", icon: Eye },
  Kasur: { label: "Kasur", icon: BedSingle },
  // Kursi: { label: "Kursi", icon: Chair },
  // Bantal: { label: "Bantal", icon: Pillow },
  // Guling: { label: "Guling", icon: Pillow },
  "Kipas Angin": { label: "Kipas Angin", icon: Fan },
  "Lemari Baju": { label: "Lemari Baju", icon: Ruler },
  Meja: { label: "Meja", icon: SquareGanttChart },
  Wastafel: { label: "Wastafel", icon: Droplets },
  Ventilasi: { label: "Ventilasi", icon: CircleDashed },
  "Water Heater": { label: "Water Heater", icon: Flame },
  AC: { label: "AC", icon: Thermometer },

  // Kategori Kamar Mandi
  "Air Panas": { label: "Air Panas", icon: Flame },
  "Bak Mandi": { label: "Bak Mandi", icon: Bath },
  Bathtub: { label: "Bathtub", icon: Bath },
  "Ember mandi": { label: "Ember Mandi", icon: Droplets },
  "K. Mandi Dalam": { label: "Kamar Mandi Dalam", icon: DoorOpen },
  "Kloset Duduk": { label: "Kloset Duduk", icon: Toilet },
  "Kloset Jongkok": { label: "Kloset Jongkok", icon: Toilet },
  Shower: { label: "Shower", icon: ShowerHead },
};

export const DEFAULT_RULE_ICON = CheckCircle;
